/*
 * Copyright (C) 2021 Gustavo García
 *
 * Este programa es software libre: puede redistribuirlo o modificarlo
 * bajo los términos de la Licencia Pública General GNU publicada por
 * la Fundación del Software Libre, ya sea la versión 3 de la Licencia
 * u, opcionalmente, cualquier versión posterior.
 *
 * Este programa se distribuye con la esperanza de que sea útil,
 * pero SIN NINGUNA GARANTÍA, ni siquiera la garantía implícita de
 * UTILIDAD COMERCIAL o SU ADECUACIÖN A CUALQUIER PROPÓSITO PARTICULAR.
 * Ver la Licencia Pública General GNU para más detalles.
 *
 * Usted debería haber recibido una copia de la Licencia Pública
 * General GNU junto con este programa. En caso contrario, vea
 * <http://www.gnu.org/licenses/>.
 */
package gui;

import db.DB;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * La ventana principal de la aplicación Dr.&nbsp;Lemmon.
 *
 * @author Gustavo García <ggarciaa at gmail.com>
 * @version 1.0
 * @since 1.0
 *
 */
public class Main extends javax.swing.JFrame {

    /**
     * Se usa para incializar la TextArea.
     */
    private static final String PROMPT = "Ingresar una idea brillante";
    /**
     * Cartel de advertencia por error del usuario.
     */
    private static final String PROMPT_NEEDED = "Es obligatorio ingresar una idea brillante";

    /**
     * Crea una instancia de la clase Main.
     * <p>
     * Llama a initComponents() para inicializar todos los componentes.
     * <p>
     * Informa por consola el path al directorio raíz del proyecto.
     * <p>
     * Selecciona la check box Informar. Propaga este setting a la clase DB.
     * <p>
     * Limpia la TextArea IdeaBrillante.
     */
    public Main() {
        initComponents();
        System.out.println(System.getProperty("user.dir"));
        cbInformar.setSelected(true);
        DB.setInformar(cbInformar.isSelected());
        taIdeaBrillante.setText(PROMPT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        spComunicaciones = new javax.swing.JScrollPane();
        taComunicaciones = new javax.swing.JTextArea();
        btnConectar = new javax.swing.JButton();
        cbInformar = new javax.swing.JCheckBox();
        btnDesconectar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        pnlIdeaBrillante = new javax.swing.JPanel();
        lblIdeaBrillante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taIdeaBrillante = new javax.swing.JTextArea();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taComunicaciones.setBackground(new java.awt.Color(204, 255, 255));
        taComunicaciones.setColumns(20);
        taComunicaciones.setLineWrap(true);
        taComunicaciones.setRows(5);
        taComunicaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        spComunicaciones.setViewportView(taComunicaciones);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        cbInformar.setText("Informar ");

        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        pnlIdeaBrillante.setBackground(new java.awt.Color(204, 255, 204));
        pnlIdeaBrillante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblIdeaBrillante.setText("Idea Brillante");

        taIdeaBrillante.setColumns(20);
        taIdeaBrillante.setRows(5);
        jScrollPane1.setViewportView(taIdeaBrillante);

        javax.swing.GroupLayout pnlIdeaBrillanteLayout = new javax.swing.GroupLayout(pnlIdeaBrillante);
        pnlIdeaBrillante.setLayout(pnlIdeaBrillanteLayout);
        pnlIdeaBrillanteLayout.setHorizontalGroup(
            pnlIdeaBrillanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdeaBrillanteLayout.createSequentialGroup()
                .addComponent(lblIdeaBrillante)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        pnlIdeaBrillanteLayout.setVerticalGroup(
            pnlIdeaBrillanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdeaBrillanteLayout.createSequentialGroup()
                .addComponent(lblIdeaBrillante, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spComunicaciones)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbInformar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar))
            .addComponent(pnlIdeaBrillante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConectar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesconectar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGrabar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConectar, btnConsultar, btnDesconectar, btnGrabar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectar)
                    .addComponent(btnDesconectar)
                    .addComponent(btnConsultar)
                    .addComponent(btnGrabar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIdeaBrillante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInformar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spComunicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConectar, btnConsultar, btnDesconectar, btnGrabar});

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     *
     * @param msg
     */
    public void appendMsg(String msg) {
        taComunicaciones.append(msg);
    }

  private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
      DB.conectar();
      updateMsg();
  }//GEN-LAST:event_btnConectarActionPerformed

  private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
      DB.desconectar();
      updateMsg();
  }//GEN-LAST:event_btnDesconectarActionPerformed

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
      DB.consultar();
      updateMsg();
  }//GEN-LAST:event_btnConsultarActionPerformed

  private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
      if (taIdeaBrillante.getText().equals(PROMPT)) {
          appendMsg(PROMPT_NEEDED);
          return;
      }
      DB.grabarIdea(taIdeaBrillante.getText());
      updateMsg();
  }//GEN-LAST:event_btnGrabarActionPerformed

  private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      taComunicaciones.setText("");
      DB.clearMsg();
  }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "pepe", "developer", null},
              
            },
            new String [] {
                "id", "nombre", "profesion",
            }
        ));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
     * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
     * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    /**
     * Actualiza el contenido de la TextArea Comunicaciones.
     *
     * @param String msg
     * @return void
     *
     */
    public void updateMsg(String msg) {
        taComunicaciones.setText(msg);
    }

    public void updateMsg() {
        taComunicaciones.setText(DB.getMsg());
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox cbInformar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblIdeaBrillante;
    private javax.swing.JPanel pnlIdeaBrillante;
    private javax.swing.JScrollPane spComunicaciones;
    private javax.swing.JTextArea taComunicaciones;
    private javax.swing.JTextArea taIdeaBrillante;
    // End of variables declaration//GEN-END:variables
}
